version: "3.8"

networks:
  my_network:
    driver: bridge

services:
  wp-db:
    image: "postgres"
    container_name: "database-postgresql"
    environment:
      - POSTGRES_USER=explore_it
      - POSTGRES_PASSWORD=explore_it123
      - POSTGRES_DB=explore_it_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: unless-stopped
  backend:
    container_name: "backend-java-spring"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - wp-db
    networks:
      - my_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wp-db:5432/explore_it_db
      - SPRING_DATASOURCE_USERNAME=explore_it
      - SPRING_DATASOURCE_PASSWORD=explore_it123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
  frontend:
    container_name: "frontend-reactjs"
    build:
      context: "../explore_it_front_end"
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network
    restart: unless-stopped
